---
- hosts: "drupal"
  become: "yes"
  roles:
    - "City-of-Bloomington.mysql"
    - "City-of-Bloomington.php"

  tasks:
    - name: "Install distro packages for Drupal"
      apt:
        name: "{{ packages }}"
        state: "present"
      vars:
        packages:
          - "php-mysql"
          - "php-gd"
          - 'poppler-utils'

    - name: "Create installation directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
      with_items:
        - "{{ drupal_install_path }}"
        - "{{ drupal_backup_path  }}"
        - "{{ drupal_site_home    }}"
        - "/var/log/cron"

    - name: "Create mysql database"
      mysql_db:
        config_file: "{{ mysql_defaults_extra_file }}"
        name: "{{ drupal_db.name }}"
        state: "present"
      no_log: "True"

    - name: "Create mysql user for site"
      mysql_user:
        name:     "{{ drupal_db.user }}"
        password: "{{ drupal_db.pass }}"
        priv:     "{{ drupal_db.name }}.*:ALL"
        state: "present"
        config_file: "{{ mysql_defaults_extra_file }}"
      no_log: "True"

    - name: "Extract release"
      ansible.builtin.unarchive:
        src:  "{{ drupal_archive_path }}"
        dest: "{{ drupal_install_path | dirname }}"
        owner: 'www-data'
        group: 'staff'

    - name: 'Link drupal config'
      file:
        state: 'link'
        src:  "{{ drupal_site_home }}"
        dest: "{{ drupal_install_path }}/web/sites/default"

    - name: "Install apache default config"
      template:
        src: "{{ lookup('first_found', paths ) }}"
        dest: "/etc/apache2/sites-available/000-default.conf"
      vars:
        paths:
          - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/templates/000-default.conf"
          - "{{ inventory_dir }}/group_vars/drupal/templates/000-default.conf"
          - "{{  playbook_dir }}/templates/000-default.conf"
      notify: "apache_restart"
      when: drupal_base_uri == "/"
      tags:
        - "apache_conf"

    - name: "Install apache site config"
      template:
        src: "{{ lookup('first_found', paths ) }}"
        dest: "/etc/apache2/sites-enabled/conf.d/drupal.conf"
      vars:
        paths:
          - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/templates/drupal.conf"
          - "{{ inventory_dir }}/group_vars/drupal/templates/drupal.conf"
          - "{{  playbook_dir }}/templates/drupal.conf"
      notify: "apache_restart"
      when: drupal_base_uri != "/"
      tags:
        - "apache_conf"

    - name: "Install CRON scripts"
      template:
        src:  "{{ item.src  }}"
        dest: "{{ item.dest }}"
        mode: "0755"
      loop:
        - { src: 'backup.sh',        dest: '/etc/cron.daily/backup.d/drupal' }
        - { src: 'asm.sh',           dest: '/etc/cron.weekly/asm' }
        - { src: 'cache-rebuild.sh', dest: '/etc/cron.hourly/drupal' }

    - name: "Update application permissions"
      file:
        path:    "{{ item }}"
        state:   "directory"
        owner:   "www-data"
        group:   "staff"
        mode:    "g+rw"
        recurse: "yes"
      with_items:
        - "{{ drupal_install_path }}"
        - "{{ drupal_backup_path  }}"
        - "{{ drupal_site_home    }}"
...
