---
- hosts: "drupal"
  become: "yes"
  roles:
    - "City-of-Bloomington.mysql"
    - "City-of-Bloomington.php"

  tasks:
    - name: "Install distro packages for Drupal"
      apt:
        name: "{{ packages }}"
        state: "present"
      vars:
        packages:
          - "php-mysql"
          - "php-gd"

    - name: "Create installation directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
      with_items:
        - "{{ drupal_install_path }}"
        - "{{ drupal_backup_path  }}"
        - "{{ drupal_site_home    }}"
        - "/var/log/cron"

    - name: "Create mysql database"
      mysql_db:
        config_file: "{{ mysql_defaults_extra_file }}"
        name: "{{ drupal_db.name }}"
        state: "present"
      no_log: "True"

    - name: "Create mysql user for site"
      mysql_user:
        name:     "{{ drupal_db.user }}"
        password: "{{ drupal_db.pass }}"
        priv:     "{{ drupal_db.name }}.*:ALL"
        state: "present"
        config_file: "{{ mysql_defaults_extra_file }}"
      no_log: "True"

    - name: "Extract release"
      unarchive:
        src: "{{ drupal_archive_path }}"
        dest: "/usr/local/src"
      register: "release"

    - name: "Remove old release"
      file:
        path: "{{ drupal_install_path }}"
        state: "absent"
      when: "release.changed"

    - name: "Install release"
      command: "rsync -rl /usr/local/src/drupal/ {{ drupal_install_path }}/"
      when: "release.changed"

    - name: "Install apache default config"
      template:
        src: "default_apache.conf"
        dest: "/etc/apache2/sites-available/000-default.conf"
      notify: "apache_restart"
      when: drupal_base_uri == "/"
      tags:
        - "apache_conf"

    - name: "Install apache site config"
      template:
        src: "subdir_apache.conf"
        dest: "/etc/apache2/sites-enabled/conf.d/drupal.conf"
      notify: "apache_restart"
      when: drupal_base_uri != "/"
      tags:
        - "apache_conf"

    - name: "Install Backup CRON"
      template:
        src: "backup.sh"
        dest: "/etc/cron.daily/backup.d/drupal"
        mode: "0755"

    - name: "Configure backup credentials"
      template:
        src: "backup.cnf"
        dest: "/etc/cron.daily/backup.d/drupal.cnf"
        mode: "0600"

    - name: "Install Cache CRON"
      template:
        src: "cache-rebuild.sh"
        dest: "/etc/cron.hourly/drupal.sh"
        mode: "0755"

    - name: "Update application permissions"
      file:
        path:    "{{ item }}"
        state:   "directory"
        owner:   "www-data"
        group:   "staff"
        mode:    "g+rw"
        recurse: "yes"
      with_items:
        - "{{ drupal_install_path }}"
        - "{{ drupal_backup_path  }}"
        - "{{ drupal_site_home    }}"
...
