<?php
/**
 * @copyright 2017-2019 City of Bloomington, Indiana
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @implements hook_help()
 */
function archive_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.archive':
            return "<h2>Google Calendar Help</h2>";
        break;
    }
}

/**
 * @implements hook_theme()
 * @see https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!theme.api.php/function/hook_theme/8.2.x
 */
function archive_theme()
{
    return [
        'archive_results'=> [
            'template' => 'archive_results',
            'variables' => [
                'year'    => null,
                'month'   => null,
                'start'   => null,
                'form'    => null,
                'type'    => null, // Node type
                'results' => [],
            ]
        ]
    ];
}
